debug = true

[jwt]
pub_key = "./conf/public.pem"
priv_key = "./conf/private.pem"
lifetime = 7200

[database]
url = "postgres://postgres:postgres@localhost:5432/daedalus"
max_connections = 10
idle_timeout = 600
connection_timeout = 30
thread_pool_size = 3

[server]
port = 8080
workers = 4

[log]
level = "debug"
format = "pretty"
